spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: ******
    password: ******
    url: jdbc:mysql://******:3306/******?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 1000MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 18080

logging:
  file:
    path: D:\\shenji

minio:
  endpoint: ******
  port: 8080
  accessKey: ******
  secretKey: ******
  secure: false
  bucketName: "audit"
  configDir: "/root/minio-data/"
