//affairReducer
export const GET_MY_AFFAIR = 'GET_MY_AFFAIR';
export const GET_TO_APPROVE = 'GET_TO_APPROVE';

export const GET_HISTORY_LOADING = 'GET_HISTORY_LOADING';
export const GET_HISTORY = 'GET_HISTORY';

//affairDetailReducer
export const GET_AFFAIR_DETAIL_LOADING = 'GET_AFFAIR_DETAIL_LOADING';
export const GET_AFFAIR_BASE_INFO = 'GET_AFFAIR_BASE_INFO';
export const GET_AFFAIR_APPROVAL_LOG = 'GET_AFFAIR_APPROVAL_LOG';
export const GET_AFFAIR_SOURCE_FILE_LIST = 'GET_AFFAIR_SOURCE_FILE_LIST';
export const GET_AFFAIR_MATERIAL_LOG = 'GET_AFFAIR_MATERIAL_LOG';

export const LOGIN = 'LOGIN';
export const GET_USER_INFO = 'GET_USER_INFO';
